# Site settings
title: Magic Mirror Sketch 3 Plugin
email: james@magicmirror.design
description: Create Perspective Mockups in Sketch. A Powerful Plugin to Perspective Transform Artboards into Shapes, just like Smart Objects in Photoshop.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
downloadurl: "http://localhost:5000/download"
author: James Tang
twitter_username: jamztang
github_username:  jamztang
analytics:
  google: UA-65727569-3
  mixpanel: 6ba7071e7855c0925266804032a85acc


# Build settings
markdown: kramdown

collections:
  templates:
    output: true
    permalink: /templates/:path/

defaults:
  - scope:
      type: templates
    values:
      layout: template
      pagename: Template # for tracking
      is_template: true
  - scope:
      type: "posts"
    values:
      pagename: Post
      is_post: true
