# Site settings
title: Magic Mirror Sketch 3 Plugin
email: james@magicmirror.design
description: A Powerful Plugin to Perspective Transform Artboards into Shapes, just like Smart Objects in Photoshop.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magicmirror.design" # the base hostname & protocol for your site
downloadurl: "http://api.magicmirror.design/download"
apigateway_url: "http://localhost:3000"
author: James Tang
twitter_username: jamztang
github_username:  jamztang
gems:
  - jekyll-redirect-from
analytics:
  google: UA-65727569-1
  mixpanel: 3cfd84dad73057910e2e1ca896a4ab6b

# Build settings
markdown: kramdown

collections:
  templates:
    output: true
    permalink: /templates/:path/
  videos:
    output: true
    permalink: /videos/:path/
  learn:
    output: true
    permalink: /learn/:path/

defaults:
  - scope:
      type: templates
    values:
      layout: template
      pagename: Template # for tracking
      is_template: true
      weight: 500
      share:
        pre: "Sketch Perspective Mockup "
        post: " for Magic Mirror"
  - scope:
      type: "posts"
    values:
      pagename: Post
      is_post: true
  - scope:
      type: videos
    values:
      layout: video
      pagename: Video # for tracking
  - scope:
      path: ""
      type: learn
    values:
      layout: learn
